# -*- coding: utf-8 -*-
"""Generators.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1E18PaI97fG-qqDIi17jttfpCrCIuFCLA
"""

def scroll(feed):
  for i in feed:
    yield i

feed = ['1-10 reels','11-20reels','21-30reels','31-40reels']
s = scroll(feed)
print(next(s))
status = 1
while True:
  msg = int(input(""))
  if msg == 1:
    print(next(s))
  else:
    break

users_db = {}

songs = {
    1: {"song": "naannaku prematho", "genre": "sad", "language": "telugu"},
    2: {"song": "follow follow", "genre": "happy", "language": "telugu"},
    3: {"song": "srivalli", "genre": "happy", "language": "telugu"},
    4: {"song": "orange", "genre": "sad", "language": "telugu"},
    5: {"song": "pushpa pushpa", "genre": "happy", "language": "telugu"},
    6: {"song": "cardigan", "genre": "happy", "language": "english"},
    7: {"song": "sorry", "genre": "sad", "language": "english"},
    8: {"song": "levitating", "genre": "happy", "language": "english"},
    9: {"song": "love story", "genre": "happy", "language": "english"},
    10: {"song": "blank space", "genre": "sad", "language": "english"},
    11: {"song": "butta bomma", "genre": "happy", "language": "telugu"},
    12: {"song": "vemulavada", "genre": "sad", "language": "telugu"},
    13: {"song": "oo antava", "genre": "happy", "language": "telugu"},
    14: {"song": "kanulanu thaake", "genre": "sad", "language": "telugu"},
    15: {"song": "watermelon sugar", "genre": "happy", "language": "english"},
    16: {"song": "someone like you", "genre": "sad", "language": "english"},
    17: {"song": "shape of you", "genre": "happy", "language": "english"},
    18: {"song": "perfect", "genre": "sad", "language": "english"},
    19: {"song": "kalavathi", "genre": "happy", "language": "telugu"},
    20: {"song": "life of ram", "genre": "sad", "language": "telugu"},
    21: {"song": "mirrors", "genre": "sad", "language": "english"},
    22: {"song": "peaches", "genre": "happy", "language": "english"},
    23: {"song": "nee kallalona", "genre": "sad", "language": "telugu"},
    24: {"song": "samajavaragamana", "genre": "happy", "language": "telugu"},
    25: {"song": "faded", "genre": "sad", "language": "english"},
    26: {"song": "sunflower", "genre": "happy", "language": "english"},
    27: {"song": "kanureppala kaalamloki", "genre": "sad", "language": "telugu"},
    28: {"song": "jigelu rani", "genre": "happy", "language": "telugu"},
    29: {"song": "as it was", "genre": "happy", "language": "english"},
    30: {"song": "drivers license", "genre": "sad", "language": "english"}
}


genre = input("Enter your genre (happy/sad): ").lower()
language = input("Choose a language (english/telugu): ").lower()
song = [ ]
for i in songs:
    if songs[i]["language"] == language and songs[i]["genre"] == genre:
        song.append(songs[i]["song"])
        print(songs[i]["song"])

def select(song):
  for i in song:
    yield i


s = select(song)
print(next(s))
status = 1
while True:
  msg = int(input(""))
  if msg == 1:
    print(next(s))
  else:
    break

